language: php
  
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          php: 7.2
        - os: linux
          dist: trusty
          sudo: false
          php: 7.3

before_script:
  - composer self-update
  - composer install
script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover ; else vendor/bin/phpunit ; fi
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TEST_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
